### ISSUE TITLE
Getting "Internal Server Error" when update configurable, downloadable, bundle and grouped product.

### ISSUE THREAD

**Issue by NishantSharma12** [bagisto/rest-api#300]
**Rest API - v2.1.2**

**Bagisto Core - v2.1.2**

**API-**

Admin -> Products -> /api/v1/admin/catalog/products/{id} Update product (Configurable, Grouped, Downloadable, Bundle)

**Configurable Product Reference Screenshot-**

![Bagisto-Admin-Rest-API-Documentation](https://github.com/bagisto/rest-api/assets/113347734/6eba652f-b29b-41ea-a76c-12f129e21074)

**Grouped Product Reference Screenshot-**

![Bagisto-Admin-Rest-API-Documentation](https://github.com/bagisto/rest-api/assets/113347734/4f4f1c50-d308-4a58-9b8a-b0d5a7ed34bf)

**Downloadable Product Reference Screenshot-**

![Bagisto-Admin-Rest-API-Documentation](https://github.com/bagisto/rest-api/assets/113347734/f8aea32e-fa7c-4303-bdf7-9392fd7779f6)

**Bundle Product Reference Screenshot-**

![Bagisto-Admin-Rest-API-Documentation (1)](https://github.com/bagisto/rest-api/assets/113347734/96b8031e-34d8-4f42-bfee-2599797d5667)

**Comment by amit-webkul** [comment]
I have checked and found that all four types of products are working fine and nicely update the values. When we are applying customer group pricing, we can face an error due to core functionality. You can check the same thing on the web, and you can also face an error with the customer group price. I have attached some screenshots for reference to updating the products without the customer group price.

![bundle-product](https://github.com/bagisto/rest-api/assets/121479029/d0d7b19c-281d-4579-880c-ccb00b527ead)
![download-product](https://github.com/bagisto/rest-api/assets/121479029/6d067591-087b-4977-87cd-812dc2cd1914)
