### ISSUE TITLE
On the Admin API -> Products -> Get product's additional info by id API -> getting same data [id and other] for different products

### ISSUE THREAD

**Issue by mukulsharma-webkul** [bagisto/rest-api#366]
**Rest API - v2.2.0**

**Bagisto Core - v2.2.0**

**Description -**

On the Admin API -> Products -> Get product's additional info by id API -> getting same data [id and other] for different products.

**Please take the reference from the video below -**

 https://webkul.chatwhizz.com/share/view-recording/66c6e45ae5f9510e2d2252fe

**Comment by amit-webkul** [comment]
I have checked and found that the API is working perfect because there are not any additional attributes added to any products, so all the products contain only the brand attribute as an additional attribute. Then this shows only brand attributes for all products in the additional attribute section.

Here is the recorded reference [video](https://webkul.chatwhizz.com/share/view-recording/66d15bd5f7a4cb09e8af6430)

**Comment by mukulsharma-webkul** [comment]
working fine, data is showing fine as per the attribute  values on the products.

**Video -**

https://webkul.chatwhizz.com/share/view-recording/66d574be8e63b50c72538b84
